# Generated by Django 3.0.8 on 2020-07-05 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='instructorlevel',
            new_name='coursetype',
        ),
        migrations.RemoveField(
            model_name='details',
            name='selfpaced',
        ),
        migrations.AddField(
            model_name='courses',
            name='startedfrom',
            field=models.DateField(default=datetime.datetime(2020, 7, 5, 21, 18, 1, 8103, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='your_choice',
            field=models.BooleanField(default=False),
        ),
    ]
