# Generated by Django 3.0.8 on 2020-07-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0002_auto_20200705_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='startedfrom',
            field=models.DateTimeField(verbose_name='Started from'),
        ),
    ]
