# Generated by Django 3.0.8 on 2020-07-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0003_auto_20200705_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='startedfrom',
        ),
    ]
