# Generated by Django 3.0.8 on 2020-07-05 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0004_remove_courses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 21, 51, 49, 825522, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
